package com.example.quickbite.android.navigation

import android.util.Log
import android.widget.Toast
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext
import androidx.navigation.NavType
import androidx.navigation.compose.*
import androidx.navigation.navArgument
import androidx.navigation.navDeepLink
import com.example.quickbite.android.screens.ClientDashboardScreen
import com.example.quickbite.android.screens.ClientOrderingScreen
import com.example.quickbite.android.screens.LiveFloorPlanScreen
import com.example.quickbite.android.screens.HomeScreen
import com.example.quickbite.android.screens.LoginScreen
import com.example.quickbite.android.screens.ProfessionalDashboardScreen
import com.example.quickbite.android.screens.ProducerDashboardScreen
import com.example.quickbite.android.screens.RegisterScreen
import com.example.quickbite.android.screens.RestaurantDashboardScreen
import com.example.quickbite.android.screens.RestaurantFeedScreen
import com.example.quickbite.android.screens.RestaurantMapScreen
import com.example.quickbite.android.screens.RoleSelectionScreen
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore

@Composable
fun AppNavHost() {
    val navController = rememberNavController()
    val context = LocalContext.current

    val startDestination = if (FirebaseAuth.getInstance().currentUser != null) "home" else "login"

    val signOut: () -> Unit = {
        FirebaseAuth.getInstance().signOut()
        navController.navigate("login") {
            popUpTo(0) { inclusive = true }
        }
    }

    NavHost(navController = navController, startDestination = startDestination) {

        composable("login") {
            LoginScreen(
                onLoginSuccess = {
                    navController.navigate("home") {
                        popUpTo("login") { inclusive = true }
                    }
                },
                onNavigateToRegister = {
                    navController.navigate("register")
                }
            )
        }

        composable("register") {
            RegisterScreen(
                onRegisterSuccess = {
                    navController.navigate("role_selection") {
                        popUpTo("register") { inclusive = true }
                    }
                },
                onBackToLogin = {
                    navController.popBackStack()
                }
            )
        }

        composable("role_selection") {
            RoleSelectionScreen(
                onRoleSelected = { role ->
                    val uid = FirebaseAuth.getInstance().currentUser?.uid
                    if (uid != null) {
                        FirebaseFirestore.getInstance()
                            .collection("users")
                            .document(uid)
                            .set(mapOf("role" to role.key))
                            .addOnSuccessListener {
                                navController.navigate("home") {
                                    popUpTo("role_selection") { inclusive = true }
                                }
                            }
                            .addOnFailureListener { e: Exception ->
                                Log.e("RoleSelection", "Failed to save role to Firestore", e)
                                Toast.makeText(
                                    context,
                                    "Eroare la salvarea rolului. Încearcă din nou.",
                                    Toast.LENGTH_LONG
                                ).show()
                            }
                    } else {
                        Toast.makeText(context, "Utilizatorul nu este autentificat.", Toast.LENGTH_SHORT).show()
                    }
                }
            )
        }

        composable("home") {
            HomeScreen(navController = navController)
        }

        composable("restaurant_dashboard") {
            RestaurantDashboardScreen(onSignOut = signOut)
        }

        composable("client_dashboard") {
            ClientDashboardScreen(
                onNavigateToOrdering = { restaurantId, tableNumber ->
                    navController.navigate("client_ordering/$restaurantId/$tableNumber")
                },
                onSignOut = signOut
            )
        }

        composable(
            route = "client_ordering/{restaurantId}/{tableNumber}",
            arguments = listOf(
                navArgument("restaurantId") { type = NavType.StringType },
                navArgument("tableNumber")  { type = NavType.IntType }
            ),
            deepLinks = listOf(
                // QR codes generated by the desktop embed: quickbite://order/{restaurantId}/{tableNumber}
                navDeepLink { uriPattern = "quickbite://order/{restaurantId}/{tableNumber}" }
            )
        ) { backStackEntry ->
            val restaurantId = backStackEntry.arguments?.getString("restaurantId") ?: return@composable
            val tableNumber  = backStackEntry.arguments?.getInt("tableNumber") ?: 1
            ClientOrderingScreen(
                restaurantId  = restaurantId,
                tableNumber   = tableNumber,
                onOrderPlaced = {
                    if (!navController.popBackStack()) {
                        navController.navigate("home") { popUpTo(0) { inclusive = true } }
                    }
                },
                onBack = {
                    if (!navController.popBackStack()) {
                        navController.navigate("home") { popUpTo(0) { inclusive = true } }
                    }
                }
            )
        }

        composable(
            route     = "live_floor_plan/{restaurantId}",
            arguments = listOf(navArgument("restaurantId") { type = NavType.StringType })
        ) { backStackEntry ->
            val restaurantId = backStackEntry.arguments?.getString("restaurantId") ?: return@composable
            LiveFloorPlanScreen(
                restaurantId         = restaurantId,
                onNavigateToOrdering = { rid, tableNum ->
                    navController.navigate("client_ordering/$rid/$tableNum")
                },
                onBack = { navController.popBackStack() }
            )
        }

        composable("producer_dashboard") {
            ProducerDashboardScreen()
        }

        composable("professional_dashboard") {
            ProfessionalDashboardScreen()
        }

        composable("restaurant_map") {
            RestaurantMapScreen(onBack = { navController.popBackStack() })
        }

        composable("restaurant_feed") {
            RestaurantFeedScreen(
                onRestaurantClick = { restaurantId, tableNumber ->
                    navController.navigate("client_ordering/$restaurantId/$tableNumber")
                },
                onSignOut = signOut
            )
        }
    }
}
